### ISSUE TITLE
how to run this project. could you explain it

### ISSUE THREAD

**Issue by aravindh1208** [prasunparate/E-Authentication-using-QR-code-and-OTP#1]

**Comment by prasunparate** [comment]
First of all you need to have software in your system to run it. (mySQL, php, any editor (like brackets), etc) .
Then put all those files in a folder and run Simple registration.html file.
This is how you can run the project.
Thanks for asking !

**Comment by aravindh1208** [comment]
Thanks bruh !
Do you have the database file

**Comment by prasunparate** [comment]
Sorry ! 
I lost that...

**Comment by MosesChirusha** [comment]
You can try to regenerate the database by inserting these columns

"roll,name,password,email,country,language,gender,address,dob,mob"

**Comment by prasunparate** [comment]
Thanks..! for your request

**Comment by MosesChirusha** [comment]
> Thanks..! for your request

Welcome, looking forward to contribute much more

**Comment by Sourabhc1** [comment]
I am not gettting any option to enter the otp..when i open that html file it asks to fill the form and when i click on submit it says new record entered..Where is otp option?

**Comment by prasunparate** [comment]
> I am not gettting any option to enter the otp..when i open that html file it asks to fill the form and when i click on submit it says new record entered..Where is otp option?

You have to create an account from which the OTP can be sent to the email that is being registered. Check the code in otp.php
