### ISSUE TITLE
after entering submit button it was downloading connect.php

### ISSUE THREAD

**Issue by Leoyut** [prasunparate/E-Authentication-using-QR-code-and-OTP#5]
have no idea was happening and how to even run this code .. help would be very much much appreciated..hope i will get the reply ....

**Comment by prasunparate** [comment]
> have no idea was happening and how to even run this code .. help would be very much much appreciated..hope i will get the reply ....

you can read readme file.

**Comment by okonjipeninah** [comment]
can i run the project using xampp?

**Comment by esanjurao** [comment]
same problem here
