### ISSUE TITLE
unable to run your project 

### ISSUE THREAD

**Issue by esanjurao** [prasunparate/E-Authentication-using-QR-code-and-OTP#6]

**Comment by esanjurao** [comment]
Fatal error: Uncaught Error: Class "mysqli" not found in C:\Users\Win10\OneDrive\Desktop\E-Authentication-using-QR-code-and-OTP-master\connect.php:14 Stack trace: #0 {main} thrown in C:\Users\Win10\OneDrive\Desktop\E-Authentication-using-QR-code-and-OTP-master\connect.php on line 14

**Comment by prasunparate** [comment]
Provide full description of the issue

**Comment by esanjurao** [comment]
After submitting this is showing

**Comment by esanjurao** [comment]
cannot post / connect.php

**Comment by esanjurao** [comment]
please help me bro 
i am in urgent need of this project

**Comment by esanjurao** [comment]
can you help me

**Comment by esanjurao** [comment]
> Provide full description of the issue

everytime i run it shows  "Cannot POST /connect.php" in a blank black page

**Comment by esanjurao** [comment]
Brother can you help me

**Comment by esanjurao** [comment]
Excuse me pls can you help me with your project of e authentication I am
unable to run this project

**Comment by prasunparate** [comment]
You have to install software's first, then have to check their paths where its been installed as per my code or change my code when you fetch it in you local.
